#ifndef PINCONFIG_H
#define PINCONFIG_H

#include <system.h>

#define PIN_NUM_PAIR_RX         		GPIO_NUM_34
#define PIN_NUM_PAIR_TX         		GPIO_NUM_33

#define PIN_NUM_SIGNAL_IN				GPIO_NUM_35

//LED control
#define PIN_NUM_LED_STROBE				GPIO_NUM_26
#define PIN_NUM_LED_OUTPUT_EN			GPIO_NUM_27
#define PIN_NUM_LED_SERIAL				GPIO_NUM_14
#define PIN_NUM_LED_CLK					GPIO_NUM_12

//Buttons
#define PIN_NUM_DOWN_BTN				GPIO_NUM_13
#define PIN_NUM_JUMP_BTN				GPIO_NUM_15
#define PIN_NUM_FIRE_BTN				GPIO_NUM_2
#define PIN_NUM_LEFT_BTN				GPIO_NUM_17
#define PIN_NUM_RIGHT_BTN				GPIO_NUM_21
#define PIN_NUM_UP_BTN					GPIO_NUM_22



//display
#define PIN_NUM_DISPLAY_BACKLIGHT 	GPIO_NUM_25
#define PIN_NUM_DISPLAY_DATA_CMD  	GPIO_NUM_4
#define PIN_NUM_DISPLAY_CS        	GPIO_NUM_16
#define PIN_NUM_SD_CS  			      GPIO_NUM_5
#define PIN_NUM_DISPLAY_SCK       	GPIO_NUM_18
#define PIN_NUM_DISPLAY_MISO      	GPIO_NUM_19
#define PIN_NUM_DISPLAY_MOSI      	GPIO_NUM_23


#define PIN_NUM_DISPLAY_RESET     	NOPIN


#endif
